language: cpp

os: linux

compiler:
    - gcc
    - clang

dist:
  - bionic
  - focal

install:
  - sudo apt update
  - sudo apt install cmake
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j $(nproc)

