language: cpp

jobs:
    include:
    - name: "Linux Bionic (GCC)"
      os: linux
      dist: bionic
      compiler: gcc
      install: .ci/travis/install_linux.sh
      script: .ci/travis/build_unix.sh
    - name: "Linux Bionic (Clang)"
      os: linux
      dist: bionic
      compiler: clang
      install: .ci/travis/install_linux.sh
      script: .ci/travis/build_unix.sh
    - name: "Linux Focal (GCC)"
      os: linux
      dist: focal
      compiler: gcc
      install: .ci/travis/install_linux.sh
      script: .ci/travis/build_unix.sh
    - name: "Linux Focal (Clang)"
      os: linux
      dist: focal
      compiler: clang
      install: .ci/travis/install_linux.sh
      script: .ci/travis/build_unix.sh
    - name: "MacOS (Clang)"
      os: osx
      compiler: clang
      install: .ci/travis/install_macos.sh
      script: .ci/travis/build_unix.sh
    - name: "Windows (Clang)"
      compiler: clang
      script: .ci/travis/build_windows.bat
