language: cpp

matrix:
    include:
        - os: linux
          dist:
              - bionic
              - focal
          compiler:
              - gcc
              - clang
          install:
              - sudo apt update
              - sudo apt install cmake
          script:
              - mkdir build
              - cd build
              - cmake ..
              - make -j $(nproc)

